### ISSUE TITLE
SDK doesn't work with Google Service

### ISSUE THREAD

**Issue by yongsunCN** [kaltura/player-sdk-native-android#76] opened 2015-12-02 20:22 UTC
To enable Google Services (such as Google Signin or Google Analytics), Google requires adding this classpath 'com.google.gms:google-services:1.5.0-beta2' into project-level gradle build file. The documentation can be found here: https://developers.google.com/identity/sign-in/android/start-integrating

After adding this classpath, the project won't build successfully, the error shows:
 Error:Execution failed for task ':playerSDK:transformNative_libsWithSyncJniLibsForDebug'.
> java.io.FileNotFoundException: /player-sdk-native-android/playerSDK/build/intermediates/bundles/debug/jni/lib/armeabi/libHLSPlayerSDK.so (No such file or directory)

To reproduce this error, simply add the following line to your example project's project level gradle and rebuild the project: 
classpath 'com.google.gms:google-services:1.5.0-beta2'

There are other people also complaining the same problem on StackOverflow: http://stackoverflow.com/questions/33959763/gradle-dependency-kaltura-player-google-analytics-incompatibility-android

**Comment by kaltura-hooks** [comment] 2015-12-02 20:30
Hi @yongsunCN,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kaltura-hooks** [comment] 2015-12-03 08:30
Hi @yongsunCN,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by noamtamim** [comment] 2015-12-03 09:02
@yongsunCN Please ignore the above automatic response, it's not relevant for the player.
Anyway, I'm looking into this issue. Which versions of Android Studio, build tools, etc are you using? Did you change the versions in our build.gradle files? 
I got this error when I tried using Android Studio 2 preview, and the matching SDK tools. It seems to be solved when I package the HLS player as an aar instead of a jar.

**Comment by noamtamim** [comment] 2015-12-03 09:19
@yongsunCN FYI, we plan to move our subcomponents to jcenter (including the Google stuff). This will help with those issues as well.

**Comment by kaltura-hooks** [comment] 2015-12-03 09:30
Hi @yongsunCN,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by noamtamim** [comment] 2015-12-03 11:17
@yongsunCN Please give branch GH-76 a try, and let me know if it fixes your issue. I was able to easily reproduce this error using your instructions, and it doesn't happen after this change.

**Comment by yongsunCN** [comment] 2015-12-03 20:44
Thanks @noamtamim for your quick response.
The GH-76 branch seems to be compatible with google service. One thing I noticed is that the sdk imports the whole play service: 'com.google.android.gms:play-services:8.1.0', which should really be only 'com.google.android.gms:play-services-cast:8.1.0'. Including the whole package will produce this error: http://stackoverflow.com/questions/32807587/com-android-build-transform-api-transformexception for larger projects

**Comment by noamtamim** [comment] 2015-12-03 20:57
@yongsunCN Thank you for this report.
As for play services, we're re-arranging our dependencies. I'll make sure this gets fixed. Thanks again.

**Comment by noamtamim** [comment] 2015-12-08 11:02
Fixed on the develop branch.

**Closed by noamtamim** 2015-12-08 11:02 UTC
