### ISSUE TITLE
Video player poor performance

### ISSUE THREAD

**Issue by BartoszJarocki** [kaltura/player-sdk-native-android#102] opened 2016-02-16 13:26 UTC
Version used:  **v2.3.0.rc4**
Environment: **Nexus 5, Android 6.0.1**, **Galaxy Nexus, Android 4.3**, **Samsung Galaxy S3, Android 4.4.4**
Steps to reproduce: **start player**

Video loading time on Android is ~10 times slower than on iOS. 
Even on your demo app loading video takes at least ~10 seconds. 
Is there any chance this will improve in feature releases? 
Is there anything we can do to improve player performance?

**Comment by kaltura-hooks** [comment] 2016-02-16 17:00
Hi @BartoszJarocki,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment] 2016-02-16 18:56
@BartoszJarocki Thank you for this report. We are aware of performance issues and are working to fix them. Yes, you should expect some improvement soon.

**Comment by BartoszJarocki** [comment] 2016-02-16 20:19
Great. Can you give me any ETA?

**Comment by kaltura-hooks** [comment] 2016-02-16 20:30
Hi @BartoszJarocki,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-android/wiki/How-To-Report-an-Issue-with-the-Kaltura-Android-Player-SDK



If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by noamtamim** [comment] 2016-02-16 20:31
Should be within a month, but I can't commit right now.
Please test with v2.4.0.rc1 and MWE v2.40.

**Comment by BartoszJarocki** [comment] 2016-02-17 15:29
Same with v2.4.0.rc1.

**Comment by pcullin-ratio** [comment] 2016-07-19 17:49
@noamtamim - what is the status of this? The issue is still open obviously, but has this been addressed? If not, is there a suitable workaround like using the web player directly?

**Comment by noamtamim** [comment] 2018-12-10 12:03
This SDK is not supported anymore, you'll have to migrate to [PlayKit](https://kaltura.github.io/playkit/).

**Closed by noamtamim** 2018-12-10 12:03 UTC
